### PR TITLE
ImuFactorExample notebook

### PR DESCRIPTION
**Pull request by varunagrawal**
This PR adds a new notebook for the `ImuFactorExample` script.

Note that I have decided to eschew the use of the `PreintegrationExample` class in favor of clarity and first principles.

### CODE REVIEW

**Review by dellaert — APPROVED** [review]
Three more requests before I merge
- remove docstring and tighten trajectory plotting code?
- say a sentence about each scenario, at least. explain what "sick" means?
- Add a conclusion section

**Comment by dellaert** [comment]
What does "@varunagrawal "enable rendering by default in colab" do?

**Comment by varunagrawal** [comment]
It allows for plots to be rendered by default, otherwise the user needs to add those 2 import lines.

**Comment by varunagrawal** [comment]
Okay, now that this is off my plate, I can go back to focusing on more pressing matters. :slightly_smiling_face:

**Comment by varunagrawal** [comment]
@dellaert I cannot merge, so please do the honors.

**Comment by dellaert** [comment]
Thanks !!!!

**Pull request merged**
